### ISSUE TITLE
Create all data schema

### ISSUE THREAD

**Issue by IndigoBee** [lexmartinez/hapi-blog#1]
> With the DB env variables configured, you can create all data schema with sequelize.sync() method see the sequelize docs

Can you explain where you would put this method and how to use it to create all data schema? 
I read the doc but I don't understand how to use it in your project :/

**Comment by lexmartinez** [comment]
Well dude as i remember you can do that from your models, there you have imported the sequelize dependency.  here you can found a short example https://gist.github.com/wellington1993/7758f5f531085b8bb99fc42622f72d56
